/**
 * ManageSpace Onboarding API
 * ManageSpace Onboarding API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SiteAmenityRequest } from './siteAmenityRequest';
import { SiteUserRequest } from './siteUserRequest';
import { GenericAddressRequestDto } from './genericAddressRequestDto';


export interface CreateDefaultDataRequest { 
    /**
     * Organization name
     */
    orgName: string;
    /**
     * Organization name
     */
    siteName: string;
    /**
     * Fields to skip during default data creation.
     */
    skip?: Array<string>;
    orgAddress?: GenericAddressRequestDto;
    siteAddress?: GenericAddressRequestDto;
    /**
     * Org Phone number
     */
    sitePhoneNumber?: string;
    /**
     * Site Phone number
     */
    orgPhoneNumber?: string;
    /**
     * Email address for the org.
     */
    orgEmail?: string;
    /**
     * Email address for the site.
     */
    siteEmail?: string;
    /**
     * Site user(s)
     */
    siteUsers?: Array<SiteUserRequest>;
    /**
     * Site amenitys(s)
     */
    siteAmenities?: Array<SiteAmenityRequest>;
    /**
     * Refresh token of the user.
     */
    refreshToken: string;
}

