/**
 * ManageSpace Onboarding API
 * ManageSpace Onboarding API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateDefaultDataRequest { 
    /**
     * Organization name
     */
    orgName: string;
    /**
     * Organization name
     */
    siteName: string;
    /**
     * Fields to skip during default data creation.
     */
    skip?: Array<string>;
    /**
     * Refresh token of the user.
     */
    refreshToken: string;
}

