/**
 * ManageSpace Onboarding API
 * ManageSpace Onboarding API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DefaultDataResponse } from './defaultDataResponse';


export interface CreateDefaultData200Response { 
    data?: Array<DefaultDataResponse>;
    success?: boolean;
    error?: object;
}

