/**
 * ManageSpace Onboarding API
 * ManageSpace Onboarding API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DefaultDataResponse { 
    /**
     * Organization ID
     */
    orgId: string;
    /**
     * Site ID
     */
    siteId: string;
    /**
     * Lease Template ID
     */
    leaseTemplateId: string;
}

